apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pvv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - uid=1000
    - gid=1000
    - allow-other
    - region us-east-1
    # - sse-kms-key-id arn:aws:kms:us-east-1:905418093184:key/36079170-58e5-4098-9852-c97fc9488b12 # set key id (optional)
    # - sse AES256
      ## change this to your desired region where your bucket is lying 
    # - allow-delete
    # - sse <aws:kms> # Use customer managed KMS key for server side encryption
    # - sse-kms-key-id <kms_key_arn> # set key id (optional)
    # - endpoint-url http://10.0.102.45:32001
    # - read-only
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: azzgamilsalahgg-s3-bucket ## replace with your bucket name 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-claim
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
  volumeName: s3-pvv
